#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ZAMETOCHKI.Droid.Resource", IsApplication=true)]

namespace ZAMETOCHKI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int sortList = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int plus = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public const int NoteHeader = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int NoteText = 2131296261;
			
			// aapt resource value: 0x7f090001
			public const int TextDate = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int TextHeader = 2131296256;
			
			// aapt resource value: 0x7f090006
			public const int featured = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int llMain = 2131296259;
			
			// aapt resource value: 0x7f09000a
			public const int menu_create = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int menu_delete = 2131296265;
			
			// aapt resource value: 0x7f09000b
			public const int menu_save = 2131296267;
			
			// aapt resource value: 0x7f090008
			public const int menu_spinner = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int spinnerItemStyle = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int toolbar = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int listViewTemplate = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Memo = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int memo_style = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int spinner_item = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int toolbar = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_menu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int memo_menu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_action_content_create = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_action_content_save = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_add_white_36dp = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_delete_white_36dp = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ic_menu_copy_holo_dark = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ic_menu_cut_holo_dark = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ic_menu_paste_holo_dark = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ic_menu_search_holo_dark = 2130903047;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CustomTextView = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int MyTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
